import Page from '../pages/page'
import StaffContacts from '../pages/staffContacts'

context('Staff contacts', () => {
  it('Staff contacts page is rendered', () => {
    cy.visit('/case/X000001/personal-details/staff-contacts')
    const page = Page.verifyOnPage(StaffContacts)
    cy.get('h2').eq(0).should('contain.text', 'Current contacts')
    cy.get('h3').eq(0).should('contain.text', 'Arhsimna Xolfo')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 0, 'Role')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 0, 'Community Offender Manager (COM) (responsible officer)')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 1, 'Phone number')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 1, '07321165373')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 2, 'Email')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 2, 'arhsimna.xolfo@moj.gov.uk')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 3, 'Provider')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 3, 'London')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 4, 'Probation Delivery Unit (PDU)')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 4, 'All London')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 5, 'Team')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 5, 'Unallocated Team (N07)')
    page.assertPageElementAtIndexWithin('dl', 0, 'dt', 6, 'Allocated from')
    page.assertPageElementAtIndexWithin('dl', 0, 'dd', 6, '22 April 2025')

    cy.get('h3').eq(1).should('contain.text', 'Bruce Wayne')
    page.assertPageElementAtIndexWithin('dl', 1, 'dt', 0, 'Role')
    page.assertPageElementAtIndexWithin('dl', 1, 'dd', 0, 'Prison Offender Manager (POM)')
    page.assertPageElementAtIndexWithin('dl', 1, 'dt', 1, 'Provider')
    page.assertPageElementAtIndexWithin('dl', 1, 'dd', 1, 'Leicester')
    page.assertPageElementAtIndexWithin('dl', 1, 'dt', 2, 'Probation Delivery Unit (PDU)')
    page.assertPageElementAtIndexWithin('dl', 1, 'dd', 2, 'Leicestershire All')
    page.assertPageElementAtIndexWithin('dl', 1, 'dt', 3, 'Team')
    page.assertPageElementAtIndexWithin('dl', 1, 'dd', 3, 'OMU B')
    page.assertPageElementAtIndexWithin('dl', 1, 'dt', 4, 'Allocated from')
    page.assertPageElementAtIndexWithin('dl', 1, 'dd', 4, '12 January 2025')

    cy.get('h2').eq(1).should('contain.text', 'Previous contacts')

    cy.get('h3').eq(2).should('contain.text', 'Yrhreender Hanandra')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 0, 'Role')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 0, 'Community Offender Manager (COM)')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 1, 'Phone number')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 1, '07321165373')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 2, 'Email')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 2, 'yrhreender.hanandra@moj.gov.uk')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 3, 'Provider')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 3, 'London')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 4, 'Probation Delivery Unit (PDU)')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 4, 'All London')
    page.assertPageElementAtIndexWithin('dl', 2, 'dt', 5, 'Team')
    page.assertPageElementAtIndexWithin('dl', 2, 'dd', 5, 'Unallocated Team (N07)')

    cy.get('h3').eq(3).should('contain.text', 'Peter Parker')
    page.assertPageElementAtIndexWithin('dl', 3, 'dt', 0, 'Role')
    page.assertPageElementAtIndexWithin('dl', 3, 'dd', 0, 'Community Offender Manager (COM)')
    page.assertPageElementAtIndexWithin('dl', 3, 'dt', 3, 'Provider')
    page.assertPageElementAtIndexWithin('dl', 3, 'dd', 3, 'London')
    page.assertPageElementAtIndexWithin('dl', 3, 'dt', 4, 'Probation Delivery Unit (PDU)')
    page.assertPageElementAtIndexWithin('dl', 3, 'dd', 4, 'N07 Cluster 1')
    page.assertPageElementAtIndexWithin('dl', 3, 'dt', 5, 'Team')
    page.assertPageElementAtIndexWithin('dl', 3, 'dd', 5, 'OMU B')
    page.assertPageElementAtIndexWithin('dl', 3, 'dt', 6, 'Allocated until')
    page.assertPageElementAtIndexWithin('dl', 3, 'dd', 6, '21 April 2024')

    cy.get('h3').eq(4).should('contain.text', 'Jon Smith')
    page.assertPageElementAtIndexWithin('dl', 4, 'dt', 0, 'Role')
    page.assertPageElementAtIndexWithin('dl', 4, 'dd', 0, 'Prison Offender Manager (POM)')
    page.assertPageElementAtIndexWithin('dl', 4, 'dt', 1, 'Provider')
    page.assertPageElementAtIndexWithin('dl', 4, 'dd', 1, 'Public Protection Unit')
    page.assertPageElementAtIndexWithin('dl', 4, 'dt', 2, 'Probation Delivery Unit (PDU)')
    page.assertPageElementAtIndexWithin('dl', 4, 'dd', 2, 'Bradford')
    page.assertPageElementAtIndexWithin('dl', 4, 'dt', 3, 'Team')
    page.assertPageElementAtIndexWithin('dl', 4, 'dd', 3, 'CPA West Yorkshire')
    page.assertPageElementAtIndexWithin('dl', 4, 'dt', 4, 'Allocated until')
    page.assertPageElementAtIndexWithin('dl', 4, 'dd', 4, '12 January 2024')
  })
})
