version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@9
  slack: circleci/slack@4.12.5

parameters:
  alerts-slack-channel:
    type: string
    # Normally team specific alert channel e.g. hmpps_tech_alerts, syscon-alerts, dps_sed_alerts
    # This is to avoid a general alert dumping ground that no-one then monitors
    default: probation-integration-notifications

  releases-slack-channel:
    type: string
    # Normally dps-releases for most teams / projects
    default: probation-integration-notifications

  node-version:
    type: string
    default: 20.13-browsers

jobs:
  build:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
