name: Cloud Platform Deploy
description: Deploy to Cloud Platform using Helm

inputs:
  environment:
    description: The environment to deploy to (dev/preprod/prod)
    required: true
  version:
    description: The version of the service to deploy
    required: true
  api:
    description: The KUBE_ENV_API
    required: true
  cert:
    description: The KUBE_CERT
    required: true
  cluster:
    description: The KUBE_CLUSTER
    required: true
  namespace:
    description: The KUBE_NAMESPACE
    required: true
  token:
    description: The KUBE_TOKEN
    required: true
  k8s_deployment_name:
    description: "Kubernetes deployment name"
    default: 'PROJECT_NAME'
    required: false
  changelog_git_paths:
    default: ""
    description: When set it will limit the file changes shown in the changelog to the specified paths only. This is useful for multi-project builds where otherwise it will show all changes from all projects.
    required: false
  show_changelog:
    description: Whether the changelog should be sent by slack
    required: false

outputs:
  deployment_changelog:
    description: "The changelog for the deployment" 
    value: ${{ steps.version_history.outputs.deployment_changelog }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Authenticate
      uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-auth@v2 # WORKFLOW_VERSION
      with:
        api: ${{ inputs.api }}
        cert: ${{ inputs.cert }}
        cluster: ${{ inputs.cluster }}
        namespace: ${{ inputs.namespace }}
        token: ${{ inputs.token }}

    - name: Get environment details 
      shell: bash
      id: env
      run: |
        case ${{ inputs.environment }} in
          'development') environment='dev' ;;
          'preproduction') environment='preprod' ;;
          'production') environment='prod' ;;     
          *) environment=${{ inputs.environment }} ;;
        esac
        echo "environment=${environment}" | tee -a "$GITHUB_OUTPUT"

    - name: get version history
      uses: ministryofjustice/hmpps-github-actions/.github/actions/version_history@v2 # WORKFLOW VERSION
      if: ${{ inputs.show_changelog }}
      id: version_history
      with:
        app_version: ${{ inputs.version }}
        environment: ${{ inputs.environment }}
        namespace: ${{ inputs.namespace }}
        k8s_deployment_name: ${{ inputs.k8s_deployment_name }}
        changelog_git_paths: ${{ inputs.changelog_git_paths }}

    - name: Deploy
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install helm
        yq -i ".appVersion = \"${{ inputs.version }}\"" "helm_deploy/${{ github.event.repository.name }}/Chart.yaml"
        helm dependency update "helm_deploy/${{ github.event.repository.name }}"
        exec helm upgrade '${{ github.event.repository.name }}' 'helm_deploy/${{ github.event.repository.name }}' \
          --atomic \
          --history-max 10 \
          --force \
          --install \
          --reset-values \
          --set 'generic-service.image.tag=${{ inputs.version }}' \
          --set 'version=${{ inputs.version }}' \
          --timeout 10m \
          --values 'helm_deploy/values-${{ steps.env.outputs.environment }}.yaml' \
          --wait
