context('Sentence', () => {
  it('Sentence page is rendered', () => {
    cy.visit('/case/X000001/sentence/offences/3')

    cy.get('h1').contains('Offences')
    cy.get('h2').contains('Additional offences')

    cy.get('section')
      .eq(0)
      .within(() => cy.get('h2').contains('Main offence'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(0).contains('Offence'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(1).contains('Category'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(2).contains('Offence date'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(3).contains('Notes'))
    cy.get('section')
      .eq(0)
      .within(() =>
        cy
          .get('dd')
          .eq(0)
          .contains('Possessing etc firearm or ammunition without firearm certificate (Group 1) - 08103 (1 count)'),
      )
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dd').eq(1).contains('Firearms offences'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dd').eq(2).contains('23 April 2024'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dd').eq(3).contains('overview'))

    cy.get('section')
      .eq(1)
      .within(() => cy.get('h2').contains('Additional offence (00600)'))
    cy.get('section')
      .eq(1)
      .within(() => cy.get('dt').eq(0).contains('Offence'))
    cy.get('section')
      .eq(1)
      .within(() => cy.get('dt').eq(1).contains('Category'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(2).contains('Offence date'))
    cy.get('section')
      .eq(1)
      .within(() => cy.get('dd').eq(0).contains('Endangering railway passengers - 00600 (1 count)'))
    cy.get('section')
      .eq(1)
      .within(() => cy.get('dd').eq(1).contains('Endangering railway passengers'))
    cy.get('section')
      .eq(1)
      .within(() => cy.get('dd').eq(2).contains('22 March 2024'))

    cy.get('section')
      .eq(2)
      .within(() => cy.get('h2').contains('Additional offence (08505)'))
    cy.get('section')
      .eq(2)
      .within(() => cy.get('dt').eq(0).contains('Offence'))
    cy.get('section')
      .eq(2)
      .within(() => cy.get('dt').eq(1).contains('Category'))
    cy.get('section')
      .eq(0)
      .within(() => cy.get('dt').eq(2).contains('Offence date'))
    cy.get('section')
      .eq(2)
      .within(() => cy.get('dd').eq(0).contains('Contravene court remedy order (S.42) - 08505 (3 counts)'))
    cy.get('section')
      .eq(2)
      .within(() => cy.get('dd').eq(1).contains('Health and Safety at Work etc Act 1974'))
    cy.get('section')
      .eq(2)
      .within(() => cy.get('dd').eq(2).contains('21 February 2024'))
  })
})
