---
# Per environment values which override defaults in hmpps-manage-a-supervision-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-a-supervision-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-a-supervision-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MAS_API_URL: "https://manage-supervision-and-delius-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    ENVIRONMENT: dev

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications